name: "StableDiffusion Ver_2.1_ High-Resolution Image Generation (512 -> 1K)"
version: "sd2.1"

diffusion:
  pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
  guidance_scale: 7.5
  diffusion_steps: 50
  target_height: 1024
  target_width: 1024

  noising_steps: 15
  freeu: False

dwt:
  steps: 5
  level: 1
  wave: "db4"
  mode: "symmetric"