name: "ModelScope High-Resolution experiments 1K"
version: "text-to-video-ms-1.7b"

prompt: "A polar bear is walking on the glacier"

negative_prompt: ""

diffusion:
  pretrained_model_name_or_path: "damo-vilab/text-to-video-ms-1.7b"
  seed: 0
  num_frames: 24
  num_inference_steps: 50

  target_height: [512, 1024]
  target_width:  [512, 1024] 
  
  denoise_start: [0, 35]
  denoise_end: [50, 50]

  num_images_per_prompt: 1
  do_classifier_free_guidance: True
  batch_size: 1
  guidance_scale: 9.0
  eta: 0.0

  save_video: True
  save_path: "./"

dwt:
  steps: 5
  level: 1
  wave: "db4"
  mode: "symmetric"